- src: https://unpkg.com/@webcomponents/custom-elements@1.6.0/custom-elements.min.js
  crossOrigin: anonymous
  referrerPolicy: no-referrer
  noModule: true
  defer: true
  integrity: sha384-O5esIhXUQcDD6TohziEoBWlKbzgaW9zKMNu+axQQu7b4w7DyfclRKFr1USqjPoMh
- src: https://unpkg.com/@shgysk8zer0/polyfills@0.5.1/browser.min.js
  crossOrigin: anonymous
  referrerPolicy: no-referrer
  integrity: sha384-ZrQRDIleCqJV8/H7xEnD+klXFyfCUpIopxnCUotsBl1OtLlaEK1VYChm0e4C50/F
  defer: true
- src: /js/index.min.js
  referrerPolicy: no-referrer
  defer: true
- src: /js/components.min.js
  referrerPolicy: no-referrer
  defer: true
