author: Chris Zuber
title: Paradise Cove Lodge
url: 'https://www.paradisecovelodge.com/'
markdown: kramdown
version: 1.1.1
timezone: America/Los_Angeles
lang: en
dir: ltr
charset: utf-8
paginate: 8
paginate_path: "/page-:num/"
viewport: width=device-width
robots: 'follow, index'
referrer: no-referrer
manifest: /manifest.json
tiles-config: /browserconfig.xml
keep-kern-clean: true
# service_worker: /service-worker.js
og-type: website
description: "Steakhouse & Motel in Lake Isabella California. Paradise Cove serves choice angus beef and quality seafood. Renovated motel rooms all have view of the lake."
mobile-web-app-capable: true
canonical: 'https://www.paradisecovelodge.com/'
keywords:
- Paradise Cove
- Paradise Cove Lodge
- lake isabella
- kern valley
- kern river valley
- dining
- lodging
- steak
- steakhouse
- lobster
- motel
- hotel
thumbnail:
  url: "/img/raster/logo.png"
facebook-site-name: paradise-cove
repository:
  username: kernvalley
  project: paradise-cove-lodge
  title: Paradise Cove
# twitter:
# feed:
#   url: /feed.rss
#   type: application/rss+xml
icons: '/img/icons.svg'
# discus-identifier:
# ad-sense:
webmaster-verifications:
  google: 4_GXTdS25bqc4x3QvWtuftfD-X2z8rlHoUyAtFPVOzo
#   bing:
defaults:
- scope:
    path: _posts
  values:
    layout: post
    author:
      givenName: Chris
      familyName: Zuber
      url: 'https://shgysk8zer0.github.io'
      gravatar: '43578597e449298f5488c2407c8a8ae5'
      github: shgysk8zer0
      twitter: shgysk8zer0
      linkedin: chris-zuber-455346141/
    publisher:
      name: 'KernValley.US'
      url: 'https://kernvalley.us'
      logo:
        url: 'https://kernvalley.us/img/icon-256.png'
    permalink: /posts/:categories/:year/:month/:day/:title/
    comments: true
    ads: false
    index: true
- scope:
    path: _drafts
  values:
    layout: post
    author:
      givenName: Chris
      familyName: Zuber
      url: 'https://shgysk8zer0.github.io'
      gravatar: '43578597e449298f5488c2407c8a8ae5'
      github: 'shgysk8zer0'
      twitter: shgysk8zer0
    publisher:
      name: 'KernValley.US'
      url: 'https://kernvalley.us'
      logo:
        url: 'https://kernvalley.us/img/icon-256.png'
    permalink: /posts/:categories/:year/:month/:day/:title/
    comments: false
    ads: false
plugins:
- jekyll-gist
- jekyll-youtube
- jekyll-admin
- jekyll-watch
- jekyll-paginate
include:
- _redirects
- _headers
- '/.well-known/'
exclude:
- ".gitkeep"
- "*.rb"
- "*.gemspec"
- "*.php"
- "*.sh"
- "*.csv"
- "*.sfd"
- "*.ai"
- "*.psd"
- "*.sketch"
- "*.yml"
- "*.lock"
- "*.log"
- "*.config.js"
- ".gitkeep"
- "tags.*"
- docs/
- "/.github/"
- Gemfile
- node_modules/
- palette.xml
- README.md
- LICENSE
- "/img/octicons/*.md"
- "/img/octicons/LICENSE"
- "/img/octicons/script"
- "/img/adwaita-icons/docs"
- "/img/adwaita-icons/LICENSE"
